jobs:
  - job: ApiPublishProdJob
    displayName: Publish API to PROD
    dependsOn: VersionBumpJob
    condition: succeeded()
    steps:
      - checkout: self

      - task: Docker@2
        displayName: Build container and publish to ACR
        inputs:
          containerRegistry: adhdevs.azurecr.io
          repository: dictura-api
          command: buildAndPush
          Dockerfile: $(System.DefaultWorkingDirectory)/api/Dictura.Api/Dockerfile
          buildContext: $(System.DefaultWorkingDirectory)/api
          tags: prod