jobs:
  - job: ApiPublishJob
    displayName: API Publish
    steps:
      - checkout: self

      - task: Docker@2
        displayName: Build container and publish to ACR
        inputs:
          containerRegistry: 'adhdevs.azurecr.io'
          repository: 'dictura-api'
          command: 'buildAndPush'
          Dockerfile: '**/api/Dictura.Api/Dockerfile'
          buildContext: '**/api'
          tags: 'dev'