trigger: none

resources:
  pipelines:
    - pipeline: devCiTriggerPipeline
      source: Dictura_DEV_CI_Trigger
      trigger:
        branches:
          include:
            - development

pool:
  vmImage: ubuntu-latest

variables:
  apiProjects: '**/*.csproj'
  apiBuildConfiguration: 'Release'
  webBuildConfiguration: 'production'
  dotnetVersion: '8.x'
  nodeVersion: '22.x'

stages:
  - stage: Initialize
    displayName: Initialize
    jobs:
      - template: templates/versioning.yml
      
      - template: templates/check-for-changes.yml
      
      - job: GithubMirrorJob
        displayName: GitHub Mirror Job
        steps:
          - template: templates/push-to-github.yml

  - stage: ApiCi
    displayName: API CI
    dependsOn: Initialize
    condition: eq(dependencies.Initialize.outputs['CheckForChanges.DetectApiChanges.result'], 'true')
    jobs:
      - template: templates/api-build.yml
      - template: templates/api-test.yml
      - template: templates/api-publish.yml

  - stage: WebCi
    displayName: Web CI
    dependsOn: Initialize
    condition: eq(dependencies.Initialize.outputs['CheckForChanges.DetectWebChanges.result'], 'true')
    jobs:
      - template: templates/web-build.yml