trigger:
  branches:
    include:
      - development

pool:
  vmImage: 'ubuntu-latest'

variables:
  major: 0
  minor: 0
  patch: 1
  versionKey: $(major).$(minor).$(patch) # Key unique for major + minor + patch combination. Ensures that build number reset when any of them changes.
  build: $[counter(variables['versionKey'], 1)] # Incremented build number

jobs:
- job: VersionBumpJob
  steps:
  - checkout: none

  # Update and print the build number
  - script: |
      echo "##vso[build.updatebuildnumber]$(major).$(minor).$(patch).$(build)"
    displayName: Set Build Name